main.js?ts=1745140420085:1144 Download the React DevTools for a better development experience: https://reactjs.org/link/react-devtools
websocket.js:48 [HMR] connected
useWeather.ts:35 Weather Data: {coord: {…}, weather: Array(1), base: 'stations', main: {…}, visibility: 10000, …}
useWeather.ts:36 Forecast Data: {cod: '200', message: 0, cnt: 40, list: Array(40), city: {…}}
index.tsx:61 Uncaught TypeError: forecast.slice is not a function
    at Home (index.tsx:61:41)
    at renderWithHooks (react-dom.development.js:16305:18)
    at updateFunctionComponent (react-dom.development.js:19583:20)
    at beginWork (react-dom.development.js:21596:16)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4164:14)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:16)
    at invokeGuardedCallback (react-dom.development.js:4277:31)
    at beginWork$1 (react-dom.development.js:27446:7)
    at performUnitOfWork (react-dom.development.js:26552:12)
    at workLoopSync (react-dom.development.js:26461:5)
    at renderRootSync (react-dom.development.js:26429:7)
    at performConcurrentWorkOnRoot (react-dom.development.js:25733:74)
    at workLoop (scheduler.development.js:266:34)
    at flushWork (scheduler.development.js:239:14)
    at MessagePort.performWorkUntilDeadline (scheduler.development.js:533:21)
Home @ index.tsx:61
renderWithHooks @ react-dom.development.js:16305
updateFunctionComponent @ react-dom.development.js:19583
beginWork @ react-dom.development.js:21596
callCallback @ react-dom.development.js:4164
invokeGuardedCallbackDev @ react-dom.development.js:4213
invokeGuardedCallback @ react-dom.development.js:4277
beginWork$1 @ react-dom.development.js:27446
performUnitOfWork @ react-dom.development.js:26552
workLoopSync @ react-dom.development.js:26461
renderRootSync @ react-dom.development.js:26429
performConcurrentWorkOnRoot @ react-dom.development.js:25733
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
index.tsx:61 Uncaught TypeError: forecast.slice is not a function
    at Home (index.tsx:61:41)
    at renderWithHooks (react-dom.development.js:16305:18)
    at updateFunctionComponent (react-dom.development.js:19583:20)
    at beginWork (react-dom.development.js:21596:16)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4164:14)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:16)
    at invokeGuardedCallback (react-dom.development.js:4277:31)
    at beginWork$1 (react-dom.development.js:27446:7)
    at performUnitOfWork (react-dom.development.js:26552:12)
    at workLoopSync (react-dom.development.js:26461:5)
    at renderRootSync (react-dom.development.js:26429:7)
    at recoverFromConcurrentError (react-dom.development.js:25845:20)
    at performConcurrentWorkOnRoot (react-dom.development.js:25745:22)
    at workLoop (scheduler.development.js:266:34)
    at flushWork (scheduler.development.js:239:14)
    at MessagePort.performWorkUntilDeadline (scheduler.development.js:533:21)
Home @ index.tsx:61
renderWithHooks @ react-dom.development.js:16305
updateFunctionComponent @ react-dom.development.js:19583
beginWork @ react-dom.development.js:21596
callCallback @ react-dom.development.js:4164
invokeGuardedCallbackDev @ react-dom.development.js:4213
invokeGuardedCallback @ react-dom.development.js:4277
beginWork$1 @ react-dom.development.js:27446
performUnitOfWork @ react-dom.development.js:26552
workLoopSync @ react-dom.development.js:26461
renderRootSync @ react-dom.development.js:26429
recoverFromConcurrentError @ react-dom.development.js:25845
performConcurrentWorkOnRoot @ react-dom.development.js:25745
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
client.js:2 The above error occurred in the <Home> component:

    at Home (webpack-internal:///./pages/index.tsx:28:76)
    at MyApp (webpack-internal:///./pages/_app.tsx:15:11)
    at PathnameContextProviderAdapter (webpack-internal:///./node_modules/next/dist/shared/lib/router/adapters.js:80:11)
    at ErrorBoundary (webpack-internal:///./node_modules/next/dist/compiled/@next/react-dev-overlay/dist/client.js:306:63)
    at ReactDevOverlay (webpack-internal:///./node_modules/next/dist/compiled/@next/react-dev-overlay/dist/client.js:858:919)
    at Container (webpack-internal:///./node_modules/next/dist/client/index.js:78:1)
    at AppContainer (webpack-internal:///./node_modules/next/dist/client/index.js:182:11)
    at Root (webpack-internal:///./node_modules/next/dist/client/index.js:372:11)

React will try to recreate this component tree from scratch using the error boundary you provided, ErrorBoundary.
console.error @ client.js:2
window.console.error @ setup-hydration-warning.js:18
logCapturedError @ react-dom.development.js:18687
callback @ react-dom.development.js:18750
callCallback @ react-dom.development.js:13923
commitUpdateQueue @ react-dom.development.js:13944
commitLayoutEffectOnFiber @ react-dom.development.js:23359
commitLayoutMountEffects_complete @ react-dom.development.js:24683
commitLayoutEffects_begin @ react-dom.development.js:24669
commitLayoutEffects @ react-dom.development.js:24607
commitRootImpl @ react-dom.development.js:26818
commitRoot @ react-dom.development.js:26677
finishConcurrentRender @ react-dom.development.js:25887
performConcurrentWorkOnRoot @ react-dom.development.js:25804
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
useWeather.ts:35 Weather Data: {coord: {…}, weather: Array(1), base: 'stations', main: {…}, visibility: 10000, …}
useWeather.ts:36 Forecast Data: {cod: '200', message: 0, cnt: 40, list: Array(40), city: {…}}
